__all__ = ["RsVideoCapture"]

class RsVideoCapture:
    def __init__(self, path: str, /, *, use_hardware: bool = False) -> None: ...
    def grab(self) -> bytes: ...
    def close(self) -> None: ...
    def width(self) -> int: ...
    def height(self) -> int: ...
